app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("worm/review", views.worm_review, name="worm_review"),
    path("worm/review/submit", views.submit_worm_verdict, name="submit_worm_verdict"),
    path("instance/submit", views.submit_chore_instance, name="submit_chore_instance"),
    # Detail page
    # path("instance/<int:pk>", )),
    # New submission link
    # path("instance/<int:pk>/submit", )),
]

worm/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static

from . import settings


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("login"))


urlpatterns = [
    path("", include("app.urls")),
    path("admin/", admin.site.urls),
    path("accounts/logout", logout_view),
    path("accounts/", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/forms.py
from django import forms
from .models import ChoreInstance, ChoreStatus


class InstanceSubmissionForm(forms.Form):
    def __init__(self, user, *args, **kwargs):
        self.instance = forms.ModelChoiceField(
            queryset=ChoreInstance.objects.filter(
                user=user, status=ChoreStatus.ASSIGNED
            )
        )

        super(forms.Form, self).__init__(*args, **kwargs)

        self.fields["instance"] = self.instance

    instance = forms.ModelChoiceField(
        queryset=ChoreInstance.objects.filter(status=ChoreStatus.ASSIGNED),
        required=True,
    )
    notes = forms.CharField(max_length=5000, required=False)
    image = forms.ImageField(
        label="Select an image",
        required=False,
        widget=forms.ClearableFileInput(attrs={"multiple": True}),
    )

app/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <title>worm</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    </head>

    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">wOrM</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="/admin">Admin</a>
                    </li>
                    {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="/worm/review">Review</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}?next=/">Logout</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <div class="container rounded">
        <div class="alert alert-info"> Hi {{ user.get_username }}</div>
        </div>

        {% if messages %}
        <div class="container rounded">
            {% for message in messages %}
            <div 
             {% if "error" in message.tags %}
             class="alert alert-danger"
             {% else %}
             class="alert alert-{{ message.tags }}"
             {% endif %}
             >
             {{ message }}
            </div>
                {% endfor %}
        </div>
        {% endif %}

        <div class="container rounded">
            {% block content %}{% endblock %}
        </div>

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

app/templates/home.html
{% extends "base.html" %}

{% block content %}
<h1>Welcome {{ user.first_name }}!</h1>

<hr>

<div>
<h4>Your weekly chore schedule</h3>
<ul>
    {% for assignment in assignments %}
    <li>
       {{ assignment }}
    </li>
    {% endfor %}
</ul>
</div>

<hr>

<div>
{% if open_instances %}
<h4>Submit a chore</h3>
    <form action="{% url 'submit_chore_instance' %}"
            method="post"
            enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
            <label for="id_instance" class="sr-only">Chore instance</label>
            <select name="instance" id="id_instance" class="form-control">
                <option value="">
                {% for x in open_instances %}
                <option value="{{ x.id }}">
                    {{ x }}
                </option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <label for="id_notes" class="sr-only">Notes</label>
            <input name="notes" id="id_notes" class="form-control" placeholder="Notes">
        </div>

        <div class="form-group">
            <label for="id_image" class="sr-only">Select images</label>
            <input type="file" name="image" multiple="" accept="image/*" id="id_image">
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% else %}
<h4>No chores available for submission</h4>
{% endif %}
</div>

<hr>

<div>
<h4>Recent submissions</h3>
{% if recent_submissions %}
<ul>
    {% for instance in recent_submissions %}
    <li>
        {{ instance }}
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No chore submissions ever... maybe you should complete a chore :|</p>
{% endif %}
    
</div>
<hr>

{% endblock %}